# Control Charts

```{r, echo=FALSE, warning=FALSE, error=FALSE, include=F}

library(ggplot2)
library(dplyr)
library(reshape2)
library(lubridate)
```

```{r, echo=FALSE, warning=FALSE, error=FALSE}

project <- Sys.getenv("PROJECT", NA)
#project <- "SKY"
if(is.na(project)) {
  project <- ""
} else { 
  project <- paste0("-", project)
}
datasetFile <- paste0("../jiraData/jiraRDataset", project, ".csv")

tsTickets <- read.csv(datasetFile, header=T, skipNul=T, na.strings="") %>%
  mutate(
    created = as.POSIXct(created), 
    resolutionDate = as.POSIXct(resolutionDate),
    resolutionMonth = as.numeric(format(resolutionDate, format="%Y%m")),
    resolutionMonthDisplay = format(resolutionDate, format="%Y %B"),
    totalTime = resolutionDate - created
  ) %>% 
  filter(status != "Closed") %>% 
  filter(status != "to do") %>% 
  filter(status != "open") %>%
  filter(ticketType != "Epic")%>% arrange(resolutionMonth)

#Get all "SecondsInColumns" data, then drop columns where we aren't working on it
workedColumns <- tsTickets %>% select(starts_with("SecondsInColumn")) %>%
  select( -one_of(c("secondsInColumns.Backlog", "secondsInColumns.Next.Up", "secondsInColumns.New", "secondsInColumns.Done", "secondsInColumns.Closed", "secondsInColumns.Resolved", "secondsInColumns.Open", "secondsInColumns.Reopened")))


```

Working columns are:

```{r, comment="", echo=FALSE, WARN=F, message=F}
paste(
  gsub("secondsInColumns.", "", colnames(workedColumns)),
  collapse=", ")

#Add up time in all the working columns
tsTickets$workTime <- apply(workedColumns, FUN="sum", MARGIN=1, na.rm=T)

minMonthLim <- floor_date(min(tsTickets$resolutionDate, na.rm =T), "month")
maxMonthLim <- ceiling_date(max(tsTickets$resolutionDate, na.rm =T), "month")


ggplot(filter(tsTickets, ! is.na(resolutionDate)), aes(x=resolutionDate, y=totalTime/24/60/60)) + geom_point() + geom_smooth(na.rm=T, fullrange=T) + ggtitle("Cycle Time - created to resolved") + ylab("Days") + xlab("Resolution Month") + expand_limits(x=c(minMonthLim, maxMonthLim))

ggplot(filter(tsTickets, ! is.na(resolutionDate)), aes(x=resolutionDate, y=workTime/24/60/60/1000)) + geom_point() + geom_smooth(na.rm=T, fullrange=T) + ggtitle("Cycle Time - Worked Time") + ylab("Days") + xlab("Resolution Month") + expand_limits(x=c(minMonthLim, maxMonthLim))

```



```{r, echo=FALSE, warning=FALSE, error=FALSE}

#ORDERING of months
tsTickets$resolutionMonthDisplay <- factor(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"], levels=unique(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"]))


ggplot(filter(tsTickets, ! is.na(resolutionMonthDisplay)), aes(x=resolutionMonthDisplay, y=workTime/24/60/60/1000)) + 
  geom_violin(scale="width", draw_quantiles=c(0.25,0.5,0.75)) + #geom_jitter(height=0, size=0.2, width=0.2) +
  theme(axis.text.x = element_text(angle=60, hjust=1)) +
  ggtitle("Velocity Violin Distribution - Worked Time") + xlab("Resolution Month") + ylab("Days")

```

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=F, fig.height=6}
source("columnColours.R")

statusLabels <- gsub("secondsInColumns.", "", names(statusColours))
names(statusLabels) <- names(statusColours)

library(lubridate)

#Join the working seconds in columns fields back with resolutionDate
controlColumns <- bind_cols(select(tsTickets, key, resolutionDate), workedColumns) %>%
  filter(! is.na(resolutionDate) ) %>% 
  filter( resolutionDate > ymd(Sys.Date()) %m-% months(3) )
nrow(controlColumns)
if (nrow(controlColumns) > 0) {
#Melt for plotting
workedMelt <- melt(controlColumns, id=c("key", "resolutionDate"))


base_breaks <- function(n = 10){
    function(x) {
        axisTicks(log10(range(x, na.rm = TRUE)), log = TRUE, nint = n)
    }
}

ggplot(workedMelt, aes(x=resolutionDate, y=value/1000/60/60/24, color=variable)) + geom_point() + ylab("Hours") + xlab("Resolution Date") + facet_wrap(~variable, ncol=2, scales="free_y") +
  scale_color_manual(values=statusColours, na.value="gray", labels=statusLabels, name="Column") + theme(legend.position="None") + geom_smooth(na.rm = T, se=T) + 
  scale_y_continuous(labels=prettyNum)
}

```

# Capex/Opex distributions

```{r, echo=F}
library(forcats)
  classOfWorkTickets <- tsTickets %>% arrange(resolutionMonth)
  classOfWorkTickets$resolutionMonthDisplay <- factor(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"], levels=unique(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"]))
  
  #Reorder so capex is on the bottom, NA on the top
  classOfWorkTickets$spendDisplay <- fct_relevel(addNA(classOfWorkTickets$spend), NA, "OPEX", "CAPEX")
  
 if (levels(classOfWorkTickets$spendDisplay) %>% length() > 1) {

  
  ggplot(filter(classOfWorkTickets, ! is.na(resolutionMonthDisplay)), aes(x=resolutionMonthDisplay, fill=NA)) + scale_fill_discrete(name=NULL) +
    geom_bar(stat="count", position="fill") + theme(legend.position = "bottom", axis.text.x = element_text(angle=60, hjust=1)) + 
    ggtitle("Spend Distribution - Completed Tickets") + xlab("Resolution Month") + ylab("Spend %")
  
    ggplot(filter(classOfWorkTickets, ! is.na(resolutionMonthDisplay)), aes(x=resolutionMonthDisplay, y=workTime, fill=spendDisplay)) + scale_fill_discrete(name=NULL) +
    geom_bar(position="fill", stat="identity") + theme(legend.position = "bottom", axis.text.x = element_text(angle=60, hjust=1)) + 
    ggtitle("Spend Distribution - Worked Time") + xlab("Resolution Month") + ylab("Spend %")
 }

```
    
Tickets where we could not see the CAPEX/OPEX assigned to them or their epic (or their epic is from a different project)

```{r, result="asis", echo=FALSE}
ticketsWithoutSpend <- classOfWorkTickets %>% filter(is.na(spend)) %>% filter(! is.na(resolutionMonthDisplay)) %>% select(key, epicLink)
knitr::kable(ticketsWithoutSpend)
```
