# Phased Cycle Time

```{r, echo=FALSE, warning=FALSE, error=FALSE, include=F}

library(ggplot2)
library(dplyr)
library(reshape2)

```

```{r, echo=FALSE, warning=FALSE, error=FALSE}
project <- Sys.getenv("PROJECT", NA)
#project <- "TS"
if(is.na(project)) {
  project <- ""
} else { 
  project <- paste0("-", project)
}
datasetFile <- paste0("../jiraData/jiraRDataset", project, ".csv")

tsTickets <- read.csv(datasetFile, header=T, skipNul=T, na.strings="") %>%
  mutate(
    created = as.POSIXct(created), 
    createdMonthDisplay = format(created, format="%Y %B"),
    createdMonth = as.numeric(format(created, format="%Y%m")),
    resolutionDate = as.POSIXct(resolutionDate), 
    resolutionMonthDisplay = format(resolutionDate, format="%Y %B"),
    resolutionMonth = as.numeric(format(resolutionDate, format="%Y%m")),
    totalTime = resolutionDate - created
  ) %>% filter(status != "Closed") %>% filter(status != "to do") %>% filter(status != "open") %>% filter(ticketType != "Epic") %>%
  select( -totalTime, -spend, -one_of(c("secondsInColumns.Open", "secondsInColumns.New", "secondsInColumns.Next.Up", "secondsInColumns.Backlog", "secondsInColumns.Resolved", "secondsInColumns.Reopened", "secondsInColumns.Closed", "secondsInColumns.Done", "secondsInColumns.Coming.Next"))) 


statusColours <- c("secondsInColumns.Open" = "white", "secondsInColumns.Backlog" = "white",
                   "secondsInColumns.Selected.for.Development" = "white",
                   "secondsInColumns.Analysis.In" = "red", "secondsInColumns.Analysis.Out" = "white",
                   "secondsInColumns.Selected" = "red",
                                      "secondsInColumns.Next" = "red",

                   "secondsInColumns.Test.Analysis.In" = "red", "secondsInColumns.Test.Analysis.Out" = "white",
                   "secondsInColumns.Test.Analysis.Done" = "white",
                   "secondsInColumns.Elaboration.In" = "red", "secondsInColumns.Elaboration.Out" = "white", "secondsInColumns.Elaboration..Out" = "white", "secondsInColumns.Elaboration.Done" = "white",
                   "secondsInColumns.Elab.In" = "red", "secondsInColumns.Elab.Out" = "white",
                   
                   "secondsInColumns.3.Amigos.In" = "red", "secondsInColumns.3.Amigos.Out" = "white",
                   "secondsInColumns.Implementation.In" = "orange", "secondsInColumns.Prioritised" = "orange",
                   "secondsInColumns.Imp.In" = "orange",
                   "secondsInColumns.Build.In" = "orange",

 "secondsInColumns.Implementation.Out" = "white", 
 "secondsInColumns.Imp.Out" = "white",
 "secondsInColumns.Build.Done" = "white",

 "secondsInColumns.Implementation.Done" = "white","secondsInColumns.Demo.d" = "white",
                   "secondsInColumns.In.Progress" = "orange",
                   
                   "secondsInColumns.Review.In" = "#ffc966", "secondsInColumns.Review.Out" = "white",
                   "secondsInColumns.Code.Review.In" = "#ffc966", "secondsInColumns.Code.Review.Out" = "white",
                   "secondsInColumns.Code.Review.Done" = "white",
                   "secondsInColumns.Awaiting.Review" = "#ffc966", "secondsInColumns.Review.Done" = "white",                           "secondsInColumns.Raise.Change" = "#ffc966", "secondsInColumns.Change.Wait" = "white",

                   "secondsInColumns.Code.Review...Demo.In" = "#ffc966", "secondsInColumns.Code.Review...Demo.Out" = "white",
                   "secondsInColumns.In.Review" = "#ffc966",
                   "secondsInColumns.Demo.In" = "#ffc966", "secondsInColumns.Demo.Out" = "white",
                   "secondsInColumns.UAT.In" = "#ffc966", "secondsInColumns.UAT.Out" = "white",
                   "secondsInColumns.BR.In" = "#ffc966", "secondsInColumns.BR.Done" = "white",
 
                   
                   "secondsInColumns.Test.In" = "yellow", "secondsInColumns.Test.Out" = "white",
                   "secondsInColumns.Testing.In" = "yellow", "secondsInColumns.Testing.Done" = "white",
                   "secondsInColumns.Test.Done" = "white",
                   
                   "secondsInColumns.Merged" = "green",
                    "secondsInColumns.Merge.In" = "green",
                    "secondsInColumns.Merge.Done" = "white",


                   "secondsInColumns.Deploy.To.Test.In" = "#00bb00",
                   "secondsInColumns.Deploy" = "#00bb00",
                   "secondsInColumns.Deploy.to.Test.Out" = "white",
                   
                   "secondsInColumns.Deployed.to.Test.Environment" = "#00bb00",
                   "secondsInColumns.Deployed.to.Staging.Environment" = "#007700",
                   "secondsInColumns.Deployed.to.Staging.Environmen" = "#007700",
                   "secondsInColumns.Staging" = "#007700",


                   "secondsInColumns.Release" = "#55bb55",
                   "secondsInColumns.Change.Imp" = "#55bb55",
                   "secondsInColumns.Release.Validation" = "#ddffdd",
                   
                   "secondsInColumns.Closed" = "#666666",
                   "secondsInColumns.Resolved" = "#666666",
                    "secondsInColumns.Done" = "#666666"

)
statusLabels <- gsub("secondsInColumns.", "", names(statusColours))
names(statusLabels) <- names(statusColours)


summaryResolved <- tsTickets %>% 
  select(-status, -ticketType, -epicLink, -created, -createdMonth, -createdMonthDisplay, -summary, -key, -resolution, -resolutionDate, -workType) %>% 
  arrange(resolutionMonth) %>%
  group_by(resolutionMonth, resolutionMonthDisplay) %>%
  summarise_all(funs(median(., na.rm = TRUE)))

summaryResolvedMelt <- melt(summaryResolved, id=c("resolutionMonthDisplay", "resolutionMonth")) %>% arrange(resolutionMonth)
#Factorise and sort the columns in reverse, so that 3Amigos is towards the left/bottom
summaryResolvedMelt$variable <- factor(summaryResolvedMelt$variable, levels = rev(levels(summaryResolvedMelt$variable)))
summaryResolvedMelt$resolutionMonthDisplay <- factor(summaryResolvedMelt[order(summaryResolvedMelt$resolutionMonth), "resolutionMonthDisplay"], levels=unique(summaryResolvedMelt[order(summaryResolvedMelt$resolutionMonth), "resolutionMonthDisplay"]))


dwellPerc <- summaryResolvedMelt %>% filter(!is.na(resolutionMonth)) %>% mutate( dwell = grepl(".out|release.validation", variable, ignore.case=T)) %>% 
  group_by(resolutionMonth, resolutionMonthDisplay, dwell) %>% 
  summarise(total=sum(value, na.rm=T)) %>% mutate( perc = round(total/sum(total)*100)) %>% filter(dwell) %>% select(resolutionMonth, resolutionMonthDisplay, perc)

dateDwell <- paste0(dwellPerc$resolutionMonthDisplay, " - (", dwellPerc$perc, "% dwell)")
names(dateDwell) <- dwellPerc$resolutionMonthDisplay

summaryResolvedMelt %>%
  filter(! is.na(resolutionMonth)) %>% #Only show resolved tickets
  ggplot(aes(x=resolutionMonthDisplay, y=value/24/60/60/1000)) + 
  geom_bar(stat="identity", aes(fill=variable)) + ylab("days") + xlab("month") +
  theme(legend.position = "bottom") + scale_fill_manual(values=statusColours, na.value="gray", labels=statusLabels, name="Column") + coord_flip() + scale_x_discrete(labels=dateDwell) + expand_limits(0) +
  guides(fill=guide_legend(reverse=TRUE)) + ggtitle("Median Phased Cycle Time - Resolved Date")

    

```

```{r, echo=FALSE, warning=FALSE, error=FALSE}

summaryResolved <- tsTickets %>%
  select(-status, -ticketType, -epicLink, -created, -createdMonth, -createdMonthDisplay, -summary, -key, -resolution, -resolutionDate) %>%
  arrange(resolutionMonth) %>%
  group_by(resolutionMonth, resolutionMonthDisplay) %>%
  summarise_all(funs(mean(., na.rm = TRUE)))

summaryResolvedMelt <- melt(summaryResolved, id=c("resolutionMonthDisplay", "resolutionMonth")) %>% arrange(resolutionMonth)
#Factorise and sort the columns in reverse, so that 3Amigos is towards the left/bottom
summaryResolvedMelt$variable <- factor(summaryResolvedMelt$variable, levels = rev(levels(summaryResolvedMelt$variable)))
summaryResolvedMelt$resolutionMonthDisplay <- factor(summaryResolvedMelt[order(summaryResolvedMelt$resolutionMonth), "resolutionMonthDisplay"], levels=unique(summaryResolvedMelt[order(summaryResolvedMelt$resolutionMonth), "resolutionMonthDisplay"]))

dwellPercMean <- summaryResolvedMelt %>% filter(!is.na(resolutionMonth)) %>% mutate( dwell = grepl(".out|release.validation", variable, ignore.case=T)) %>% 
  group_by(resolutionMonth, resolutionMonthDisplay, dwell) %>% 
  summarise(total=sum(value, na.rm=T)) %>% mutate( perc = round(total/sum(total)*100)) %>% filter(dwell) %>% select(resolutionMonth, resolutionMonthDisplay, perc)

dateDwellMean <- paste0(dwellPercMean$resolutionMonthDisplay, " - (", dwellPercMean$perc, "% dwell)")
names(dateDwellMean) <- dwellPercMean$resolutionMonthDisplay


summaryResolvedMelt %>%
  filter(! is.na(resolutionMonth)) %>% #Only show resolved tickets
  ggplot(aes(x=resolutionMonthDisplay, y=value/24/60/60/1000)) +
  geom_bar(stat="identity", aes(fill=variable)) + ylab("days") + xlab("month") +
  theme(legend.position = "bottom") + scale_fill_manual(values=statusColours, na.value="gray", labels=statusLabels, name="Column") + coord_flip() + scale_x_discrete(labels=dateDwellMean) +
  guides(fill=guide_legend(reverse=TRUE)) + ggtitle("Mean Phased Cycle Time - Resolved Date")
```

```{r, echo=FALSE, warning=FALSE, error=FALSE}

dwellPercMeasures <- inner_join(dwellPerc, dwellPercMean, by=c("resolutionMonth", "resolutionMonthDisplay"), suffix = c(".median", ".mean"))

dwellPercMelt <- dwellPercMeasures %>% melt(id=c("resolutionMonthDisplay", "resolutionMonth"), value.name="Percentage", variable.name="Measure")

 
ggplot(dwellPercMelt, aes(x=resolutionMonthDisplay, y=Percentage, group=Measure, color=Measure)) + geom_line(linetype="dashed", alpha=0.5) + theme(axis.text.x = element_text(angle=60, hjust=1), legend.position = "bottom") + ggtitle("Percentage of time tickets spend in a 'dwell' column") + expand_limits(y=c(0,100)) + geom_smooth(se=F, method="loess")

```