# Work Type

```{r, echo=FALSE, warning=FALSE, error=FALSE, include=F}

library(ggplot2)
library(dplyr)
library(reshape2)
library(gtools)

```

```{r, echo=FALSE, warning=FALSE, error=FALSE}

tsTickets <- read.csv("/Users/grovesro/Desktop/jiraR/jiraRDataset.csv", header=T, skipNul=T, na.strings="") %>%
  mutate(
    created = as.POSIXct(created), 
    createdMonthDisplay = format(created, format="%Y %B"),
    createdMonth = as.numeric(format(created, format="%Y%m")),
    resolutionDate = as.POSIXct(resolutionDate), 
    resolutionMonthDisplay = format(resolutionDate, format="%Y %B"),
    resolutionMonth = as.numeric(format(resolutionDate, format="%Y%m")),
    totalTime = resolutionDate - created
  ) %>% filter(status != "Closed") %>% filter(status != "to do") %>% filter(status != "open") %>% filter(ticketType != "Epic")

if ( length(unique(tsTickets$workType)) > 1) {
  classOfWorkTickets <- tsTickets %>% arrange(resolutionMonth)
  classOfWorkTickets$resolutionMonthDisplay <- factor(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"], levels=unique(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"]))
  
  g1 <- ggplot(filter(classOfWorkTickets, ! is.na(resolutionMonthDisplay)), aes(x=resolutionMonthDisplay, fill=workType)) + scale_fill_discrete(name=NULL) +
    geom_bar(stat="count", position="fill") + theme(legend.position = "bottom", axis.text.x = element_text(angle=60, hjust=1)) + 
    ggtitle("Work Type Distribution") + xlab("Resolution Month") + ylab("Work Type %")
  
  print(g1)
  g2 <- ggplot(filter(classOfWorkTickets, ! is.na(resolutionMonthDisplay)), aes(x=resolutionMonthDisplay, fill=workType)) + scale_fill_discrete(name=NULL) +
    geom_bar(stat="count") + theme(legend.position="bottom", axis.text.x = element_text(angle=90, hjust=1)) + facet_wrap(~ workType) + 
    ggtitle("Completed Tickets by Work Type") + xlab("Resolution Month") + ylab("Tickets Resolved")
  print(g2)
  
} else {
  #print("No Work Types are set")
}
```

```{r, echo=FALSE, warning=FALSE, error=FALSE}

if ( length(unique(tsTickets$epicLink)) > 1) {
  classOfWorkTickets <- tsTickets %>% arrange(resolutionMonth)
  classOfWorkTickets$resolutionMonthDisplay <- factor(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"], levels=unique(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"]))
  
  classOfWorkTickets$epicLink <- factor(classOfWorkTickets$epicLink, levels = gsub(" ", "-", mixedsort(gsub("-", " ",levels(classOfWorkTickets$epicLink)))))

  
  g1 <- ggplot(filter(classOfWorkTickets, ! is.na(resolutionMonthDisplay)), aes(x=resolutionMonthDisplay, fill=epicLink)) + 
    geom_bar(stat="count", position="fill") + theme(axis.text.x = element_text(angle=60, hjust=1)) + 
    ggtitle("Class Of Epic Distribution") + xlab("Resolution Month") + ylab("Class Of Work %")
  
  print(g1)
  
  
  
  g2 <- ggplot(filter(classOfWorkTickets, ! is.na(resolutionMonthDisplay)), aes(x=resolutionMonthDisplay, fill=epicLink)) + 
    geom_bar(stat="count") + theme(axis.text.x = element_text(angle=90, hjust=1), legend.position = "right") + facet_wrap(~ epicLink) + 
    ggtitle("Class Of Epic") + xlab("Resolution Month") + ylab("Tickets Resolved")
  print(g2)
} else {
  print("No Epic Links are set")
}
```