# Velocity

```{r, echo=FALSE, warning=FALSE, error=FALSE, include=F}

library(ggplot2)
library(dplyr)
library(reshape2)

```

```{r, echo=FALSE, warning=FALSE, error=FALSE}

tsTickets <- read.csv("/Users/grovesro/Desktop/jiraR/jiraRDataset.csv", header=T, skipNul=T, na.strings="") %>%
  mutate(
    created = as.POSIXct(created), 
    createdMonthDisplay = format(created, format="%Y %B"),
    createdMonth = as.numeric(format(created, format="%Y%m")),
    resolutionDate = as.POSIXct(resolutionDate), 
    resolutionMonthDisplay = format(resolutionDate, format="%Y %B"),
    resolutionMonth = as.numeric(format(resolutionDate, format="%Y%m")),
    totalTime = resolutionDate - created
  ) %>% filter(status != "Closed") %>% filter(status != "to do") %>% filter(status != "open") %>% filter(ticketType != "Epic")


resolvedTickets <- tsTickets %>% arrange(resolutionMonth)
resolvedTickets$resolutionMonthDisplay <- factor(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"], levels=unique(tsTickets[order(tsTickets$resolutionMonth), "resolutionMonthDisplay"]))

ggplot(filter(resolvedTickets, ! is.na(resolutionMonthDisplay)), aes(x=resolutionMonthDisplay)) + 
  geom_freqpoly(stat="count", group=1) + theme(axis.text.x = element_text(angle=60, hjust=1)) +
  ggtitle("Velocity") + xlab("Resolution Month") + ylab("Tickets Resolved")

ggplot(filter(resolvedTickets, ! is.na(resolutionMonthDisplay)), aes(x=resolutionMonthDisplay)) + 
  geom_bar(stat="count") + theme(axis.text.x = element_text(angle=60, hjust=1)) +
  ggtitle("Velocity") + xlab("Resolution Month") + ylab("Tickets Resolved")

ggplot(filter(resolvedTickets, ! is.na(resolutionMonthDisplay)), aes(x=resolutionMonthDisplay, y=totalTime/24/60/60)) + 
  geom_violin(scale="width", draw_quantiles=c(0.5,0.75)) + #geom_jitter(height=0, size=0.2, width=0.2) +
  theme(axis.text.x = element_text(angle=60, hjust=1)) +
  ggtitle("Velocity Violin Distribution") + xlab("Resolution Month") + ylab("Days")

#Pretty but date order is broken
#reatedTickets <- tsTickets %>% arrange(createdMonth)
#createdTickets$createdMonthDisplay <- factor(tsTickets[order(tsTickets$createdMonth), "createdMonthDisplay"], levels=unique(tsTickets[order(tsTickets$createdMonth), "createdMonthDisplay"]))
#ggplot(tsTickets, aes(x=createdMonthDisplay, group=!is.na(resolution), color=!is.na(resolution))) + stat_ecdf(geom="line") + scale_color_discrete("Resolved") +
#  theme(axis.text.x = element_text(angle=60, hjust=1)) + ggtitle("Burnup Percentage") + ylab("Percentage Burnup") + xlab("Month")
```